### ISSUE TITLE
comparing coalescent simulators

### ISSUE THREAD

**Issue by alanrogers** [scrm/scrm#126]
I'm corresponding with Dick Hudson and Jerome Kelleher about discrepancies between ms, msprime, and scrm. I'd like to include Paul Staab in this conversation, but the email I have for him bounces. If Paul would like to get in touch, my email is rogers@anthro.utah.edu. Meanwhile, here is what I sent to Dick and Jerome:

[coalsim.pdf](https://github.com/scrm/scrm/files/2604746/coalsim.pdf)

**Comment by paulstaab** [comment]
Hallo Alan,

can you check if the results for scrm change with version 1.7.3? We just changed the behavior of scrm when multiple -ej, -es or -eps events happen at the same time - which is the case in your model - to be similar to ms. 

If multiple events happen at the same time, are they executed sequentially or all at once, e.g. If you have -ej 1.0 1 2 -ej 1.0 2 1 do you get an infinite circle because lines that arrived in pop 1 go back to pop 2 (all events executed at once), or is each event just executed once and all line end up in pop2 (executed sequentially).

In scrm we had originally opted for executed at once, but now changed the behavior to be similar to ms.

I don't know how msprime handels this, but it could be a possible explanation for the difference you are seeing. Maybe.

Best,
Paul 


Von meinem iPhone gesendet

**Comment by paulstaab** [comment]
The problem was resolved and luckly had nothing to do with scrm.
