### ISSUE TITLE
-l 0 option not giving SMC' trees? 

### ISSUE THREAD

**Issue by ismael2395** [scrm/scrm#127]
Hi, 

I have encountered a problem when trying to generate trees from a SMC' process (with recombination). According to the documentation I should be able to simulate this process by specifying the `-l 0` flag. However, the trees that I obtain don't seem to follow this process. 
Here is the version of scrm I am using and the command I tried to run: 

```
./scrm --version 
scrm 1.7.3

scrm 10 1 -T -r 1 2200 -eN 0 3000 -p 10 -l 0 -seed 0
```

After extracting  trees from this output and looking at some of them. It does not seem like the trees can be produced from a SMC' process. In particular, I was looking at the 17th and 18th tree from the output above. The coalescent times of these trees: 

```
[1,] 11.82869 57.39018 70.83035 156.62978 265.6850 931.8015 1023.383 1068.948 7928.051
[2,] 11.82869 57.39018 70.83035  81.70056 156.6298 265.6850 1023.383 1068.948 5176.707
```

And a plot of the trees: 

<img width="981" alt="image" src="https://user-images.githubusercontent.com/11745764/51353834-988eea00-1a66-11e9-9555-77e9adfe20fc.png">

Don't make sense to me given the Markovian SMC' definition given in this paper (see figure 2 for instance): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4566269/ 

Could it be that you are using a different SMC' definition or a different approximation? 

Thank you in advance! and, sorry for the long post! 

Ismael

**Comment by paulstaab** [comment]
Hi Ismael,

despite the continuous modelling of sequence in coalescent models, the `-T` output by default only displays trees which are valid at the position of "base pairs", i.e. at integer positions on the continuous, real valued chromosome. That means that there is a slightly weird but useful rounding of the sequence length that the trees are valid, and more importantly for our case, there can be more than one recombination event between the trees in the output., e.g because there were 5 recombination events between two base pairs.

You can use the "-SC rel" option to output all trees with their actual real value sequence length. Can you please add this option in your example, and check if there is more than one recombination event between the trees you have shown, and confirm if consecutive trees are consistent with the SMC' model?

Thank you!
Paul

**Comment by paulstaab** [comment]
I am closing this issue for now. Fell free to reopen it if you feel that there still might be a problem.
